GET http://localhost:5099/games
###

GET http://localhost:5099/games/1
###

POST http://localhost:5099/games
Content-Type: application/json

{
  "title": "Final Fantasy VII",
  "genreId": 4,
  "price": 59.99,
  "releaseDate": "1990-11-02"
}
###

PUT http://localhost:5099/games/3
Content-Type: application/json

{
  "id": 1,
  "title": "Gothic II Noc Kruka",
  "genreId": "0",
  "releaseDate": "2026-04-30",
  "price": -29.99
}
###

DELETE http://localhost:5099/games/6
###

GET http://localhost:5099/genres/ 
###